'use client';

import { styled } from '@mui/material';

export const StyledInner = styled('div')({
  width: 'calc(100% - clamp(40px,8vw,96px))',
  maxWidth: 1440,
  margin: '0 auto',
  '@media (max-width: 600px)': {
    width: 'calc(100% - 48px)',
  },
});

export const StyledCredentialsIntro = styled('section')(({ theme }) => ({
  padding: 'clamp(94px,11vw,170px) 0 clamp(70px,8vw,118px)',
  borderBottom: `1px solid ${theme.palette.divider}`,
  background: theme.palette.background.default,
  '& .credentials-intro-grid': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0,1.35fr) minmax(300px,.65fr)',
    gap: 'clamp(48px,8vw,128px)',
    alignItems: 'end',
  },
  '& h1': {
    maxWidth: 930,
    margin: 0,
    fontFamily: 'var(--font-display)',
    fontSize: 'clamp(3.4rem,7.4vw,7.6rem)',
    fontWeight: 440,
    lineHeight: 0.92,
    letterSpacing: '-.058em',
  },
  '& .credentials-intro-copy': {
    display: 'grid',
    gap: 34,
  },
  '& .credentials-intro-copy > p': {
    maxWidth: 590,
    margin: 0,
    color: theme.palette.text.secondary,
    fontSize: 'clamp(1rem,1.25vw,1.16rem)',
    lineHeight: 1.78,
  },
  '& .credentials-intro-detail': {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 20,
    paddingTop: 17,
    borderTop: `1px solid ${theme.palette.divider}`,
    color: theme.palette.text.secondary,
    fontSize: '.86rem',
    lineHeight: 1.5,
  },
  [theme.breakpoints.down('md')]: {
    '& .credentials-intro-grid': {
      gridTemplateColumns: '1fr',
      gap: 38,
    },
    '& .credentials-intro-copy': { maxWidth: 720 },
  },
  [theme.breakpoints.down('sm')]: {
    paddingTop: 76,
    '& h1': {
      fontSize: 'clamp(2.8rem,14vw,4.6rem)',
      lineHeight: 0.96,
    },
    '& .credentials-intro-detail': {
      gridTemplateColumns: '1fr',
      gap: 7,
    },
  },
}));

export const StyledSection = styled('section')(({ theme }) => ({
  padding: 'clamp(66px,8vw,126px) 0 clamp(92px,10vw,160px)',
  overflow: 'clip',
  background: theme.palette.background.paper,
}));

export const StyledCredentialsNote = styled('div')(({ theme }) => ({
  display: 'grid',
  gridTemplateColumns: 'minmax(170px,.34fr) minmax(0,1fr)',
  gap: 'clamp(24px,4vw,64px)',
  maxWidth: 920,
  padding: '22px 0',
  marginBottom: 'clamp(70px,9vw,130px)',
  borderTop: `1px solid ${theme.palette.divider}`,
  borderBottom: `1px solid ${theme.palette.divider}`,
  '& strong': {
    alignSelf: 'start',
    fontSize: '.94rem',
    fontWeight: 700,
  },
  '& p': {
    maxWidth: 660,
    margin: 0,
    color: theme.palette.text.secondary,
    lineHeight: 1.75,
  },
  [theme.breakpoints.down('sm')]: {
    gridTemplateColumns: '1fr',
    gap: 9,
  },
}));

export const StyledCredentialRegister = styled('div')({
  display: 'grid',
  gap: 'clamp(92px,12vw,180px)',
});

export const StyledCredentialGroup = styled('section')(({ theme }) => ({
  display: 'grid',
  gridTemplateColumns: 'minmax(220px,.34fr) minmax(0,1fr)',
  gap: 'clamp(42px,7vw,108px)',
  paddingTop: 26,
  borderTop: `1px solid ${theme.palette.divider}`,
  '& > header': {
    alignSelf: 'start',
    position: 'sticky',
    top: 112,
  },
  '& > header h2': {
    maxWidth: 320,
    margin: 0,
    fontFamily: 'var(--font-display)',
    fontSize: 'clamp(2rem,3vw,3.4rem)',
    fontWeight: 470,
    lineHeight: 1,
    letterSpacing: '-.035em',
  },
  '& > header p': {
    maxWidth: 330,
    margin: '20px 0 0',
    color: theme.palette.text.secondary,
    lineHeight: 1.75,
  },
  '& .credential-documents': {
    display: 'grid',
    gridTemplateColumns: 'repeat(12,minmax(0,1fr))',
    gap: 'clamp(50px,7vw,96px) clamp(18px,2.6vw,38px)',
    alignItems: 'start',
  },
  '& figure': {
    minWidth: 0,
    margin: 0,
  },
  '& figure.feature': { gridColumn: 'span 7' },
  '& figure.standard': { gridColumn: 'span 5', marginTop: 'clamp(60px,8vw,118px)' },
  '& figure.wide': { gridColumn: '1 / span 10' },
  '& .credential-document-button': {
    width: '100%',
    display: 'block',
    padding: 0,
    border: 0,
    borderRadius: 0,
    background: 'transparent',
    textAlign: 'left',
    cursor: 'zoom-in',
  },
  '& .credential-document-button:focus-visible': {
    outline: `3px solid ${theme.palette.primary.main}`,
    outlineOffset: 6,
  },
  '& .document-preview': {
    position: 'relative',
    width: '100%',
    padding: 'clamp(12px,1.8vw,22px)',
    background: '#dcd6ca',
    boxShadow: '0 24px 60px rgba(35,29,20,.12)',
    transition: 'transform 360ms cubic-bezier(.22,1,.36,1), box-shadow 360ms ease',
  },
  '& .credential-document-button:hover .document-preview': {
    transform: 'translateY(-4px)',
    boxShadow: '0 32px 72px rgba(35,29,20,.16)',
  },
  '& .document-preview-feature, & .document-preview-standard': { aspectRatio: '3 / 4' },
  '& .document-preview-wide': { aspectRatio: '10 / 7' },
  '& .document-tone-sand': { background: '#d8cebc' },
  '& .document-tone-ivory': { background: '#e2ddd2' },
  '& .document-tone-stone': { background: '#d1d0ca' },
  '& .document-tone-warm': { background: '#d9cfc6' },
  '& .document-page': {
    position: 'relative',
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    padding: 'clamp(24px,4vw,58px)',
    border: '1px solid rgba(86,69,40,.34)',
    background: '#fbf9f3',
    color: '#171714',
  },
  '& .document-brand': {
    display: 'grid',
    gridTemplateColumns: '54px 1fr',
    gap: 20,
    alignItems: 'center',
    marginBottom: 'clamp(30px,5vw,68px)',
  },
  '& .document-brand span': {
    width: 54,
    height: 54,
    display: 'grid',
    placeItems: 'center',
    border: '1px solid #755f37',
    color: '#755f37',
    fontWeight: 800,
    fontSize: '.85rem',
  },
  '& .document-brand i': {
    display: 'block',
    height: 1,
    background: '#755f37',
  },
  '& .document-status': {
    margin: 0,
    color: '#755f37',
    fontSize: '.72rem',
    fontWeight: 800,
    letterSpacing: '.08em',
    textTransform: 'uppercase',
  },
  '& .document-page h3': {
    maxWidth: '86%',
    margin: 'clamp(18px,2vw,30px) 0 0',
    fontFamily: 'var(--font-display)',
    fontSize: 'clamp(1.7rem,3.3vw,4.2rem)',
    fontWeight: 470,
    lineHeight: .98,
    letterSpacing: '-.045em',
  },
  '& .document-summary': {
    maxWidth: '84%',
    margin: 'clamp(18px,2.5vw,34px) 0 0',
    color: '#66635d',
    lineHeight: 1.65,
    fontSize: 'clamp(.76rem,1.1vw,1rem)',
  },
  '& .document-page dl': {
    display: 'grid',
    gap: 0,
    margin: 'clamp(30px,5vw,72px) 0 0',
  },
  '& .document-page dl > div': {
    display: 'grid',
    gap: 7,
    padding: 'clamp(13px,1.7vw,21px) 0',
    borderTop: '1px solid rgba(86,69,40,.28)',
  },
  '& .document-page dt': {
    color: '#755f37',
    fontSize: '.68rem',
    fontWeight: 800,
    letterSpacing: '.05em',
    textTransform: 'uppercase',
  },
  '& .document-page dd': {
    margin: 0,
    fontSize: 'clamp(.78rem,1.1vw,.98rem)',
    lineHeight: 1.45,
  },
  '& .document-watermark': {
    position: 'absolute',
    left: '44%',
    top: '51%',
    transform: 'rotate(28deg)',
    color: 'rgba(117,95,55,.09)',
    fontSize: 'clamp(3.2rem,8vw,8rem)',
    fontWeight: 800,
    letterSpacing: '.06em',
    pointerEvents: 'none',
  },
  '& .document-stamp': {
    width: 'clamp(92px,11vw,138px)',
    aspectRatio: '1',
    display: 'grid',
    placeItems: 'center',
    alignSelf: 'flex-end',
    marginTop: 'auto',
    padding: 14,
    border: '3px double #755f37',
    borderRadius: '50%',
    color: '#755f37',
    fontSize: 'clamp(.56rem,.8vw,.72rem)',
    fontWeight: 800,
    lineHeight: 1.15,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  '& .document-page > small': {
    marginTop: 20,
    color: '#858078',
    fontSize: '.66rem',
  },
  '& figcaption': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0,1fr) auto',
    gap: '6px 22px',
    paddingTop: 18,
    marginTop: 17,
    borderTop: `1px solid ${theme.palette.divider}`,
  },
  '& figcaption h3': {
    margin: 0,
    fontSize: 'clamp(1.2rem,1.55vw,1.62rem)',
    lineHeight: 1.24,
  },
  '& figcaption p': {
    margin: '5px 0 0',
    color: theme.palette.text.secondary,
    lineHeight: 1.55,
  },
  '& .document-open-cue': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    alignSelf: 'start',
    color: theme.palette.text.primary,
    fontSize: '.84rem',
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  '& figcaption small': {
    gridColumn: 1,
    color: theme.palette.primary.dark,
    fontSize: '.78rem',
    fontWeight: 700,
    lineHeight: 1.5,
  },
  '& figcaption em': {
    gridColumn: 1 / -1,
    marginTop: 5,
    color: theme.palette.text.secondary,
    fontSize: '.8rem',
    fontStyle: 'normal',
    lineHeight: 1.55,
  },
  [theme.breakpoints.down('lg')]: {
    gridTemplateColumns: 'minmax(200px,.3fr) minmax(0,1fr)',
    gap: 54,
    '& figure.feature, & figure.standard': { gridColumn: 'span 6' },
    '& figure.standard': { marginTop: 58 },
    '& figure.wide': { gridColumn: '1 / -1' },
  },
  [theme.breakpoints.down('md')]: {
    gridTemplateColumns: '1fr',
    '& > header': { position: 'static', maxWidth: 620 },
    '& > header p': { maxWidth: 560 },
  },
  [theme.breakpoints.down('sm')]: {
    gap: 38,
    paddingTop: 20,
    '& .credential-documents': {
      gridTemplateColumns: '1fr',
      gap: 58,
    },
    '& figure.feature, & figure.standard, & figure.wide': {
      gridColumn: '1',
      marginTop: 0,
    },
    '& .document-preview-feature, & .document-preview-standard': { aspectRatio: '3 / 4' },
    '& .document-preview-wide': { aspectRatio: '10 / 7' },
    '& .document-page': { padding: 24 },
    '& .document-page h3': { fontSize: 'clamp(1.65rem,8.5vw,2.5rem)' },
    '& .document-summary': { maxWidth: '94%', fontSize: '.78rem' },
    '& .document-page dl': { marginTop: 30 },
    '& .document-page dl > div': { padding: '12px 0' },
    '& .document-brand': { marginBottom: 28, gridTemplateColumns: '46px 1fr' },
    '& .document-brand span': { width: 46, height: 46 },
    '& figcaption': { gridTemplateColumns: '1fr' },
    '& .document-open-cue': { minHeight: 44, marginTop: 6 },
    '& figcaption small, & figcaption em': { gridColumn: 1 },
  },
  '@media (prefers-reduced-motion: reduce)': {
    '& .document-preview': { transition: 'none' },
    '& .credential-document-button:hover .document-preview': { transform: 'none' },
  },
}));

export const StyledCredentialLightbox = styled('div')(({ theme }) => ({
  position: 'fixed',
  inset: 0,
  zIndex: 1200,
  display: 'grid',
  gridTemplateColumns: '64px minmax(0,1fr) 64px',
  alignItems: 'center',
  gap: 18,
  padding:
    'max(24px, env(safe-area-inset-top)) max(24px, env(safe-area-inset-right)) max(24px, env(safe-area-inset-bottom)) max(24px, env(safe-area-inset-left))',
  background: 'rgba(12,12,11,.95)',
  backdropFilter: 'blur(12px)',
  animation: 'credentialLightboxIn 200ms ease both',
  '@keyframes credentialLightboxIn': { from: { opacity: 0 }, to: { opacity: 1 } },
  '& > button': {
    width: 52,
    height: 52,
    display: 'grid',
    placeItems: 'center',
    padding: 0,
    border: '1px solid rgba(255,255,255,.34)',
    borderRadius: 0,
    background: 'rgba(0,0,0,.26)',
    color: '#fff',
    cursor: 'pointer',
  },
  '& > button:focus-visible': {
    outline: '3px solid #fff',
    outlineOffset: 3,
  },
  '& .close': {
    position: 'absolute',
    top: 'max(20px, env(safe-area-inset-top))',
    right: 'max(20px, env(safe-area-inset-right))',
    zIndex: 2,
  },
  '& .previous': { gridColumn: 1 },
  '& .next': { gridColumn: 3 },
  [theme.breakpoints.down('sm')]: {
    gridTemplateColumns: '1fr',
    gridTemplateRows: 'minmax(0,1fr) 56px',
    gap: 12,
    padding:
      'max(72px, calc(env(safe-area-inset-top) + 60px)) 16px max(16px, env(safe-area-inset-bottom))',
    '& .previous, & .next': {
      position: 'absolute',
      bottom: 'max(14px, env(safe-area-inset-bottom))',
    },
    '& .previous': { left: 16 },
    '& .next': { right: 16 },
  },
  '@media (prefers-reduced-motion: reduce)': {
    animation: 'none',
  },
}));

export const StyledCredentialLightboxDocument = styled('div')(({ theme }) => ({
  gridColumn: 2,
  minWidth: 0,
  maxHeight: 'calc(100svh - 68px)',
  display: 'grid',
  gridTemplateRows: 'minmax(0,1fr) auto',
  justifyItems: 'center',
  gap: 14,
  '& .document-preview': {
    height: 'min(72svh,820px)',
    width: 'auto',
    maxWidth: 'min(72vw,980px)',
    padding: 16,
    background: '#d9d2c5',
    boxShadow: '0 28px 90px rgba(0,0,0,.36)',
  },
  '& .document-preview-feature, & .document-preview-standard': { aspectRatio: '3 / 4' },
  '& .document-preview-wide': {
    width: 'min(78vw,1040px)',
    height: 'auto',
    aspectRatio: '10 / 7',
  },
  '& .document-page': {
    position: 'relative',
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    padding: 'clamp(28px,4vw,58px)',
    border: '1px solid rgba(86,69,40,.34)',
    background: '#fbf9f3',
    color: '#171714',
  },
  '& .document-brand': {
    display: 'grid',
    gridTemplateColumns: '54px 1fr',
    gap: 20,
    alignItems: 'center',
    marginBottom: 'clamp(28px,4vw,58px)',
  },
  '& .document-brand span': {
    width: 54,
    height: 54,
    display: 'grid',
    placeItems: 'center',
    border: '1px solid #755f37',
    color: '#755f37',
    fontWeight: 800,
    fontSize: '.85rem',
  },
  '& .document-brand i': { display: 'block', height: 1, background: '#755f37' },
  '& .document-status': {
    margin: 0,
    color: '#755f37',
    fontSize: '.72rem',
    fontWeight: 800,
    letterSpacing: '.08em',
    textTransform: 'uppercase',
  },
  '& .document-page h3': {
    maxWidth: '86%',
    margin: '20px 0 0',
    fontFamily: 'var(--font-display)',
    fontSize: 'clamp(2rem,4vw,4.6rem)',
    fontWeight: 470,
    lineHeight: .98,
    letterSpacing: '-.045em',
  },
  '& .document-summary': {
    maxWidth: '84%',
    margin: '24px 0 0',
    color: '#66635d',
    lineHeight: 1.65,
  },
  '& .document-page dl': { display: 'grid', gap: 0, margin: 'clamp(32px,4vw,60px) 0 0' },
  '& .document-page dl > div': {
    display: 'grid',
    gap: 7,
    padding: '16px 0',
    borderTop: '1px solid rgba(86,69,40,.28)',
  },
  '& .document-page dt': {
    color: '#755f37',
    fontSize: '.68rem',
    fontWeight: 800,
    letterSpacing: '.05em',
    textTransform: 'uppercase',
  },
  '& .document-page dd': { margin: 0, fontSize: '.94rem', lineHeight: 1.45 },
  '& .document-watermark': {
    position: 'absolute',
    left: '43%',
    top: '50%',
    transform: 'rotate(28deg)',
    color: 'rgba(117,95,55,.09)',
    fontSize: 'clamp(4rem,10vw,9rem)',
    fontWeight: 800,
    letterSpacing: '.06em',
  },
  '& .document-stamp': {
    width: 118,
    aspectRatio: '1',
    display: 'grid',
    placeItems: 'center',
    alignSelf: 'flex-end',
    marginTop: 'auto',
    padding: 14,
    border: '3px double #755f37',
    borderRadius: '50%',
    color: '#755f37',
    fontSize: '.64rem',
    fontWeight: 800,
    lineHeight: 1.15,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  '& .document-page > small': { marginTop: 18, color: '#858078', fontSize: '.66rem' },
  '& .lightbox-caption': {
    width: 'min(760px,100%)',
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    gap: '4px 20px',
    color: '#fff',
  },
  '& .lightbox-caption strong': { fontSize: '1rem' },
  '& .lightbox-caption span': { gridColumn: 1, color: 'rgba(255,255,255,.68)', fontSize: '.86rem' },
  '& .lightbox-caption small': {
    gridColumn: 2,
    gridRow: '1 / span 2',
    alignSelf: 'center',
    color: 'rgba(255,255,255,.68)',
  },
  [theme.breakpoints.down('sm')]: {
    gridColumn: 1,
    maxHeight: 'calc(100svh - 142px)',
    '& .document-preview': {
      width: 'min(92vw,430px)',
      height: 'auto',
      maxHeight: 'calc(100svh - 230px)',
      padding: 9,
    },
    '& .document-preview-feature, & .document-preview-standard': { aspectRatio: '3 / 4' },
    '& .document-preview-wide': { width: 'min(92vw,560px)', aspectRatio: '10 / 7' },
    '& .document-page': { padding: 20 },
    '& .document-brand': { gridTemplateColumns: '42px 1fr', gap: 13, marginBottom: 22 },
    '& .document-brand span': { width: 42, height: 42 },
    '& .document-page h3': { fontSize: 'clamp(1.45rem,7vw,2.4rem)', marginTop: 14 },
    '& .document-summary': { marginTop: 15, fontSize: '.72rem', lineHeight: 1.45 },
    '& .document-page dl': { marginTop: 20 },
    '& .document-page dl > div': { padding: '9px 0', gap: 4 },
    '& .document-page dt': { fontSize: '.56rem' },
    '& .document-page dd': { fontSize: '.68rem' },
    '& .document-stamp': { width: 78, padding: 9, fontSize: '.47rem' },
    '& .document-page > small': { marginTop: 9, fontSize: '.52rem' },
    '& .lightbox-caption': { gridTemplateColumns: '1fr', paddingInline: 4 },
    '& .lightbox-caption small': { gridColumn: 1, gridRow: 'auto' },
  },
}));
