import type { Metadata } from 'next';
import Link from 'next/link';
import { Typography } from '@mui/material';
import { LegalPage } from '@/features/legal/LegalPage';

export const metadata: Metadata = { title: 'Privacy Policy', description: 'How Lyn Bactad Property Group collects, uses, shares, and protects personal information.', alternates: { canonical: '/privacy' } };

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" description="How Lyn Bactad Property Group handles personal information submitted through this website.">
    <section><Typography variant="h2">1. Who we are</Typography><Typography>Lyn Bactad Property Group operates this website and acts as the personal information controller for personal information collected through it. This notice is intended to explain our processing in clear language and is guided by the Philippine Data Privacy Act of 2012 and its implementing rules.</Typography></section>
    <section><Typography variant="h2">2. Information we collect</Typography><Typography>When you send an inquiry, we collect the information you choose to provide, which may include:</Typography><ul><li>your name, contact number, and email address;</li><li>the inquiry type, preferred property type, property reference, and property-related details; and</li><li>your message and any details you include in it.</li></ul><Typography>On a property page, the website records an aggregate view count for that listing and day. It uses browser session storage to avoid sending the same page-view event repeatedly in one browser tab session. We also temporarily use IP address information in memory to limit abusive or excessive requests. Please do not include sensitive personal information or documents in a website inquiry unless we specifically ask for them through an appropriate channel.</Typography></section>
    <section><Typography variant="h2">3. Why we use your information</Typography><Typography>We process personal information to:</Typography><ul><li>receive, assess, and respond to your property or general inquiry;</li><li>identify the relevant listing and coordinate your inquiry with the assigned or appropriate broker;</li><li>operate, secure, troubleshoot, and improve the website, including aggregated listing-view measurement; and</li><li>comply with applicable legal obligations and address disputes or legal claims.</li></ul><Typography>Depending on the context, processing is based on your consent or request for a response, steps connected with a requested transaction, our legitimate interests in operating and securing the website, or a legal obligation. We do not use inquiry information for solely automated decisions that produce legal or similarly significant effects.</Typography></section>
    <section><Typography variant="h2">4. Who may receive it</Typography><Typography>We may share an inquiry with the broker assigned to the referenced property or another appropriate broker so the inquiry can be handled. We may also use service providers that support hosting, database, security, or website operation. They may process information only as needed to provide those services or as required by law. We do not sell or rent personal information.</Typography><Typography>If a service provider processes information outside the Philippines, we will use safeguards appropriate to the transfer and applicable law.</Typography></section>
    <section><Typography variant="h2">5. Retention and security</Typography><Typography>We retain inquiry information only for as long as it is reasonably needed to respond, manage follow-up, meet legal obligations, establish or defend legal claims, or maintain legitimate business records. Retention needs are reviewed periodically; information that is no longer needed should be securely deleted or de-identified, subject to applicable law.</Typography><Typography>We use administrative and technical measures designed to protect information from unauthorized access, loss, misuse, or disclosure. No internet transmission or storage system can be guaranteed completely secure.</Typography></section>
    <section><Typography variant="h2">6. Your privacy rights</Typography><Typography>Subject to the conditions and limits in applicable law, you may request to be informed about processing of your personal information; access or correct it; object to certain processing; withdraw consent; request erasure or blocking where applicable; request data portability where applicable; seek damages; or file a complaint.</Typography><Typography>To make a request, use our <Link href="/contact">contact page</Link> and clearly state that it is a privacy request. We may need to verify your identity before acting. You may also raise a concern with the Philippine National Privacy Commission through its <a href="https://privacy.gov.ph/file-a-complaint-2/" target="_blank" rel="noreferrer">complaint process</a>.</Typography></section>
    <section><Typography variant="h2">7. Updates to this policy</Typography><Typography>We may update this policy when our practices, services, or legal obligations change. The current version and its effective date will always appear on this page.</Typography></section>
  </LegalPage>;
}
