import type { Metadata } from 'next';
import Link from 'next/link';
import { Typography } from '@mui/material';
import { LegalPage } from '@/features/legal/LegalPage';

export const metadata: Metadata = { title: 'Terms of Use', description: 'Terms governing use of the Lyn Bactad Property Group website and property listings.', alternates: { canonical: '/terms' } };

export default function TermsPage() {
  return <LegalPage title="Terms of Use" description="The terms that apply when you browse this website, view a listing, or contact Lyn Bactad Property Group.">
    <section><Typography variant="h2">1. Acceptance and scope</Typography><Typography>These Terms of Use govern your access to and use of the Lyn Bactad Property Group website. By using the website, you agree to these terms. If you do not agree, please do not use the website.</Typography><Typography>These terms apply to the website and its public property listings. A separate written agreement may apply to a brokerage engagement, property viewing, reservation, sale, lease, or other transaction. If there is a conflict, that written agreement controls for the relevant transaction.</Typography></section>
    <section><Typography variant="h2">2. Listings and information</Typography><Typography>Listings are provided for general information and may change, be withdrawn, or become unavailable without notice. Prices, availability, lot or floor areas, photographs, descriptions, locations, access details, and other listing information should be independently confirmed with the assigned broker before you rely on them or make a decision.</Typography><Typography>Website content is not legal, tax, financial, engineering, appraisal, or survey advice. It is not an offer, acceptance, reservation, or guarantee that a property will be available, suitable, or sold or leased on any terms.</Typography></section>
    <section><Typography variant="h2">3. Inquiries and broker coordination</Typography><Typography>You may submit an inquiry through the website. Please provide accurate contact details and do not submit another person&apos;s information unless you are authorized to do so. We may route a property-related inquiry to the assigned broker or another appropriate broker so that it can be handled.</Typography><Typography>Sending an inquiry does not create a broker-client relationship, agency relationship, viewing appointment, or transaction. Those arrangements arise only when separately agreed.</Typography></section>
    <section><Typography variant="h2">4. Acceptable use</Typography><Typography>You must not use the website in a way that is unlawful, harmful, or interferes with its operation. In particular, you must not:</Typography><ul><li>submit false, misleading, infringing, abusive, or unauthorized information;</li><li>attempt to bypass security, probe for vulnerabilities, or interfere with the website or its users;</li><li>use automated tools to scrape, harvest, copy, or repeatedly access the website without prior written permission; or</li><li>use listing information for an unlawful, deceptive, or unauthorized commercial purpose.</li></ul></section>
    <section><Typography variant="h2">5. Intellectual property and links</Typography><Typography>The website&apos;s design, text, branding, and other content are owned by or used with permission by Lyn Bactad Property Group or their respective rights holders. You may view and use them for personal, lawful property research. You may not reproduce, modify, distribute, or commercially exploit them without permission, except where applicable law allows it.</Typography><Typography>The website may link to third-party services or pages. Those services are governed by their own terms and privacy practices. We do not control or endorse their content or availability.</Typography></section>
    <section><Typography variant="h2">6. Disclaimers and liability</Typography><Typography>The website is provided on an “as available” basis. To the extent permitted by applicable law, Lyn Bactad Property Group does not make warranties about uninterrupted availability, error-free operation, or the completeness, accuracy, or suitability of website content. Nothing in these terms excludes liability that cannot lawfully be excluded.</Typography></section>
    <section><Typography variant="h2">7. Changes, governing law, and contact</Typography><Typography>We may update these terms by posting the revised version here and changing the date above. Your continued use after an update means you accept the revised terms. These terms are governed by the laws of the Republic of the Philippines, without limiting any mandatory consumer protection rights that may apply.</Typography><Typography>For questions about these terms, please use our <Link href="/contact">contact page</Link>.</Typography></section>
  </LegalPage>;
}
